Webcore/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("core.urls")),
    path("", include("user.urls")),
    path("", include("chatbot.urls")),
    path("", include("blog.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from blog import views


app_name='blog'
urlpatterns = [
    path("blog/", views.blog_index, name="blog_index"),
    path("blog/<int:pk>/", views.blog_detail, name="blog_detail"),
    path("blog/<category>/", views.blog_category, name="blog_category"),
]

core/urls.py
from django.urls import path
from core import views
from .models import LogMessage


home_list_view = views.HomeListView.as_view(
    queryset=LogMessage.objects.order_by("-log_date")[:5], # :5 limits the results to the five most recent
    context_object_name="message_list",
    template_name="core/home.html",
)
app_name='core'
urlpatterns = [
    
    path("home", home_list_view, name="home"),
    path("", views.visitor, name="visitor"),
    path("about/", views.about, name="about"),
    path("contact/", views.contact, name="contact"),
    path("log/", views.log_message, name="log")

]

user/urls.py
from django.urls import path,re_path
from user import views
from django.contrib.auth.views import logout_then_login

app_name='user'
urlpatterns = [
    path("signin/", views.signin, name="signin"),
    path("signup/", views.signup, name="signup"),
    path("logout/",  views.signout, name="logout"),
    path("profile/",  views.get_user_profile, name="profile"),
]

core/models.py
from django.db import models
from django.utils import timezone
# Create your models here.


class LogMessage(models.Model):
    message = models.CharField(max_length=300)
    log_date = models.DateTimeField("date logged")

    def __str__(self):
        """Returns a string representation of a message."""
        date = timezone.localtime(self.log_date)
        return f"'{self.message}' logged on {date.strftime('%A, %d %B, %Y at %X')}"

core/forms.py
from django import forms
from core.models import LogMessage

class LogMessageForm(forms.ModelForm):
    class Meta:
        model = LogMessage
        fields = ("message",)   # NOTE: the trailing comma is required

core/views.py
import re
from django.shortcuts import render, redirect
from django.http import HttpResponse
from datetime import datetime
from .forms import LogMessageForm
from .models import LogMessage
from django.views.generic import ListView
# Create your views here.

# def home(request):
#     return render(request,
#     'core/home.html')

class HomeListView(ListView):
    model= LogMessage

    def get_context_data(self, **kwargs):
        context = super(HomeListView, self).get_context_data(**kwargs)
        return context

def visitor(request):
    return render(request,
    'core/index.html')

def about(request):
    return render(request,
    'core/about.html',
    )

def contact(request):
    return render(request,
    'core/contact.html',
    )

def log_message(request):
    form = LogMessageForm(request.POST or None)

    if request.method == "POST":
        if form.is_valid():
            message = form.save(commit=False)
            message.log_date = datetime.now()
            message.save()
            return redirect("core:home")
    else:
        return render(request, "core/log_message.html", {"form": form})

core/templates/core/include/aboutus.html
<div class="container-fluid" id="aboutus">
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-8">
        <h2>About Company Page</h2>
        <h4>Lorem ipsum..</h4>
        <p>Admiration we surrounded possession frequently he. Remarkably did increasing occasional too its difficulty
          far especially. Known tiled but sorry joy balls. Bed sudden manner indeed fat now feebly. Face do with in need
          of wife paid that be. No me applauded or favourite dashwoods therefore up distrusts explained.</p>
        
      </div>
 
      <div class="col-sm-4">
        <i class="icon ion-md-trending-up logo">
        </i>
      </div>
    </div>
  </div>

  <div class="container-fluid">
    <div class="row">

      <div class="col-sm-8">
        <h2>Our Values</h2>
        <h4><strong>MISSION:</strong> Our mission lorem ipsum..</h4>
        <p><strong>VISION:</strong> Surprise steepest recurred landlord mr wandered amounted of. Continuing devonshire
          but considered its. Rose past oh shew roof is song neat. Do depend better praise do friend garden an wonder
          to. Intention age nay otherwise but breakfast. Around garden beyond to extent by.
        </p>
      </div>
      <div class="col-sm-4">
        <i class="icon ion-md-globe logo"></i>
         
      </div>
    </div>
  </div>
</div>

core/templates/core/include/carousel.html
{% load static %}
<div class="container-fluid text-center" id="carousel">
    <h3>What our Customer's have to say</h3>
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
            <div class="carousel-item active">
 
                    <h4>"This company is the best. I am so happy with the result!"<br><span
                            style="font-style:normal;">Michael Roe, Vice President, Comment Box</span></h4>

            </div>
            <div class="carousel-item">

                    <h4>"This company is the best. I am so happy with the result!"<br><span
                            style="font-style:normal;">Michael Roe, Vice President, Comment Box</span></h4>

            </div>
            <div class="carousel-item">

   
                    <h4>"This company is the best. I am so happy with the result!"<br><span
                            style="font-style:normal;">Michael Roe, Vice President, Comment Box</span></h4>
                
            </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
</div>

core/templates/core/include/cont.html
<div class="container-fluid" id="contact">
    <h2 class="text-center">CONTACT</h2>
    <div class="row slideanim">
        <div class="col-sm-5">
            <p>Swing by for a cup of coffee, or leave us a message.</p>
            <p> <span> <i class="material-icons">
                location_on
                </i></span> Chicago, US</p>
            <p><span> <i class="material-icons">
                phone
                </i></span>+00 1515151515</p>
            <p><span> <i class="material-icons">
                mail
                </i></span>  myemail@something.com</p>
                    
        </div>
        <div class="col-sm-7">
            <div class="row">
                <div class="col-sm-6 form-group">
                    <input class="form-control" id="name" name="name" placeholder="Name" type="text" required>
                </div>
                <div class="col-sm-6 form-group">
                    <input class="form-control" id="email" name="email" placeholder="Email" type="email" required>
                </div>
            </div>
            <textarea class="form-control" id="comments" name="comments" placeholder="Comment" rows="5"></textarea><br>
            <div class="row">
                <div class="col-sm-12 form-group">
                    <button class="btn btn-default pull-right" type="submit">Send</button>
                </div>
            </div>
        </div>
    </div>
</div>

core/templates/core/include/footer.html
<footer class="footer">
        
          <span class="text-muted">Copyrights 2019 Relax and Enjoy.</span>
      
      </footer>

core/templates/core/include/jumbotron.html
<div class="jumbotron jumbotron-fluid">
  <div class="container-fluid">
    <h1>Adventure</h1>
    <div>The Mountains are calling still I must go <span id="typed"></span></div>
  </div>
</div>

core/templates/core/include/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="navBar">
               
        <a class="navbar-brand" href="{% url 'core:visitor' %}">MCO</a>
        <!-- <a class="navbar-brand" href="#index">MCO</a> -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navCollapse">
                <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navCollapse">

                <ul class="navbar-nav mr-auto">
                        {% if user.is_authenticated %}
                        <li class="nav-item">
                                <a class="nav-link" href="{% url 'core:home' %}">Home</a>
                        </li>
                        <li class="nav-item">
                                <a class="nav-link" href="{% url 'core:log' %}">Log Message</a>
                        </li>
                        <li class="nav-item">
                                <a class="nav-link" href="{% url 'core:contact' %}">Contact</a>
                        </li>
                        <li class="nav-item">
                                        <a class="nav-link" href="{% url 'user:profile' %}">Profile</a>
                                </li>
                        <li class="nav-item">
                                <a class="nav-link" href="{% url 'user:logout' %}">Logout</a>
                        </li>
                        {% else %}
                        <li class="nav-item">
                                <!-- <a class="nav-link" href="{% url 'core:about' %}">About</a> -->
                                <a class="nav-link" href="#aboutus">About</a>
                        </li>
                                                <li class="nav-item">
                                <a class="nav-link" href="#proser">Services</a>
                                </li>
                        <li class="nav-item">
                                        <a class="nav-link" href="#portfolio">Portfolio</a>
                        </li>
                        <li class="nav-item">
                                <!-- <a class="nav-link" href="{% url 'core:contact' %}">About</a> -->
                                <a class="nav-link" href="#contact">Contact</a>
                        </li>
                        <li class="nav-item">
                                <a class="nav-link" href="{% url 'blog:blog_index' %}">Blog</a>
                        </li>

                        <li class="nav-item">
                                <a class="nav-link" href="{% url 'user:signup' %}">Sign Up</a>
                        </li>
                        <li class="nav-item">
                                <a class="nav-link" href="{% url 'user:signin' %}">Log In</a>
                        </li>
                        {% endif %}
                </ul>
        </div>
</nav>
<button class="btn btn-primary arrow up" onclick="topFunction()" id="scrollBtn" title="Top"> <span><i class="material-icons">
                keyboard_arrow_up
                </i></span></button>

core/templates/core/include/portfolio.html
{% load static %}

<div class="container-fluid text-center" id="portfolio"> 
    <h2>PORTFOLIO</h2>
    <h3>Our creation
    </h3>
    <div class="row slideanim">
      <div class="col-sm-4">
        <div class="thumbnail">
          <img src="{% static 'core/images/cr1.jpg' %}" alt="Paris">
          <p><strong>Paris</strong></p>
          <p>Yes, we built Paris</p>
        </div>
      </div>
      <div class="col-sm-4">
        <div class="thumbnail">
          <img src="{% static 'core/images/cr2.jpg' %}" alt="New York">
          <p><strong>New York</strong></p>
          <p>We built New York</p>
        </div>
      </div>
      <div class="col-sm-4">
        <div class="thumbnail">
          <img src="{% static 'core/images/cr3.jpg' %}" alt="San Francisco">
          <p><strong>San Francisco</strong></p>
          <p>Yes, San Fran is ours</p>
        </div>
      </div>

</div>

core/templates/core/include/proser.html
<div class="container-fluid text-center" id="proser">
    <h2>SERVICES</h2>
    <h4>What we offer</h4>
    <br>
    <div class="row slideanim">
      <div class="col-sm-4">
        <span > <i class="material-icons logo-small">
          power_settings_new
          </i></span>
        <h4>POWER</h4>
        <p>Lorem ipsum dolor sit amet..</p>
      </div>
      <div class="col-sm-4">
        <span><i class="material-icons logo-small">
          favorite
          </i></span>
        <h4>LOVE</h4>
        <p>Lorem ipsum dolor sit amet..</p>
      </div>
      <div class="col-sm-4">
        <span><i class="material-icons logo-small">
          work
          </i></span>
        <h4>JOB DONE</h4>
        <p>Lorem ipsum dolor sit amet..</p>
      </div>
      </div>
      <br><br>
    <div class="row slideanim">
      <div class="col-sm-4">
        <span><i class="material-icons logo-small">
          autorenew
          </i></span>
        <h4>GREEN</h4>
        <p>Lorem ipsum dolor sit amet..</p>
      </div>
      <div class="col-sm-4">
        <span><i class="material-icons logo-small">
          assignment_turned_in
          </i></span>
        <h4>CERTIFIED</h4>
        <p>Lorem ipsum dolor sit amet..</p>
      </div>
      <div class="col-sm-4">
        <span><i class="material-icons logo-small">
          group_work
          </i></span>
        <h4>HARD WORK</h4>
        <p>Lorem ipsum dolor sit amet..</p>
      </div>
    </div>

</div>

core/templates/core/include/scattertext.html
<div class="container-fluid" id="scatter">
    <div id="loader"></div>
  <div id="soup-container">
    <div id="segments">
    </div>
    <div id="soup-nav">
      <span id="soup-prev"><span class="carousel-control-prev-icon" aria-hidden="true"></span></span>
      <span id="soup-next"><span class="carousel-control-next-icon" aria-hidden="true"></span></span>
    </div>
</div>
</div>